FROM ubuntu:20.04

#
# Skip interactive mode
#
ENV DEBIAN_FRONTEND=noninteractive

#
# Add Ondrej PPA
#
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php -y


#
# Install Nginx and latest PHP version 8.0.3
#
RUN apt-get update		    \
    && apt-get install -y	\
    nginx			        \
    sqlite3			        \
    php8.0-fpm		        \
    php8.0-mysql		    \
    php8.0-intl			    \
    php8.0-mbstring		    \
    php8.0-zip		        \
    php8.0-xml		        \
    php8.0-sqlite3

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/7.4/fpm/php.ini
COPY docker/php_cli.ini /etc/php/7.4/cli/php.ini
COPY docker/default /etc/nginx/sites-available/default
COPY docker/mhsendmail /usr/local/bin/mhsendmail

EXPOSE 80

#
# Adding MailHog support
# set default address to 127.0.0.1
#
ENV MAILHOG_SMTP_IP_ADDR=127.0.0.1

WORKDIR /var/www/html

CMD service php7.4-fpm start 	\
    && nginx -g 'daemon off;'	\
    && bash
